spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 570010894402-klafsenr5vknp3i87gnjm2pjfsdgh39c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
