spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/out-cry
    username: outcry_app
    password: outcry1!
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 5000